- include: check_vars.yml tags=redis,redis:check,check

- include: redis_install.yml tags=redis,redis:install
- include: redis_configure.yml tags=redis,redis:config

- include: redis_sentinel.yml tags=redis,redis:sentinel
  when: redis_sentinel_server_group | default(false)

- include: redis_datadog.yml tags=redis,redis:redis:sentinel,datadog,redis:datadog
  when: datadog_enabled | default(false)

- include: redis_backup.yml tags=redis,redis:sentinel,datadog,backup
  when: redis_rdb_backup_keep > 0
